accounts/urls.py
from django.urls import path
from . import views
app_name='accounts'

urlpatterns = [
    path('login/', views.my_login, name='my_login'),
    path('logout/', views.my_logout, name='my_logout'),
    path('signup/', views.my_signup, name='my_signup'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from polls.views import hello
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('polls.urls')),
    path('accounts/', include('accounts.urls')),
    path('photo_gallery/', include('photo_gallery.urls')),
    path('search/', include('polls.urls')),
    
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

polls/urls.py
from django.urls import path
from . import views

app_name = 'polls'

urlpatterns = [
    # path('', views.good, name='home'),
    path('', views.index, name='index'),
    path('sans', views.sans, name='sans'),
    path('papyrus', views.papyrus, name='papyrus'),
    path('memo/', views.memo_list, name='memo_list'),
    path('my_memo/', views.my_memo_list, name='my_memo_list'),
    path('memo/create/', views.memo_create, name='memo_create'),
    path('<int:pk>/', views.memo_detail, name='memo_detail'),
    path('<int:pk>/update/', views.memo_update, name='memo_update'),
    path('<int:pk>/delete/', views.memo_delete, name='memo_delete'),
    path('memo/<int:memo_id>', views.one_memo, name='one_memo'),
    path('art_create', views.art_create, name='art_create'),
    path('memo_search', views.memo_search, name='memo_search'),
    # path('hello/', views.hello, name='hello'),
    # path('lion/<str:name>/', views.lion, name='lion'),
    # path('good/', views.good, name='good'),
    # path('moon/', views.moon, name='moon'),
    # path('add/<int:num1>/<int:num2>/', views.add),
    # path('multiply/<int:num1>/<int:num2>/', views.multiply),
    #path('memo/stats/', views.memo_stats, name='memo_stats'),
]

templates/common/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.7/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-LN+7fdVzj6u52u30Kp6M/trliBMCMKTyK833zpbD+pXdCLuTusPj697FH4R/5mcr" crossorigin="anonymous">
        <style>
        /* 기본 스타일 */
        .navbar-nav .nav-link {
            font-family: Arial, sans-serif;
        }
        
        /* 각 페이지별 글씨체 클래스 */
        .papyrus-theme .navbar-nav .nav-link,
        .papyrus-theme button {
            font-family: Papyrus, fantasy;
            font-weight: bold;
        }
        
        .comic-theme .navbar-nav .nav-link,
        .comic-theme button {
            font-family: 'Comic Sans MS', cursive;
            font-weight: bold;
        }
        
        .undertale-theme .navbar-nav .nav-link,
        .undertale-theme button {
            font-family: 'Courier New', monospace;
            font-weight: bold;
        }
    </style>
</head>
<body class="{% block style_class %}{% endblock %}">

{%  block style %}
{% endblock %}
<nav class="navbar navbar-expand-lg bg-body-tertiary">
<div class="container-fluid">
  <a class="navbar-brand" href="#">Navbar</a>
  <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
      <li class="nav-item">
        <a class="nav-link active" aria-current="page" href="{% url 'polls:index' %}">Home</a>
      </li>
      <li class="nav-item">
        <a class="nav-link active" aria-current="page" href="{% url 'polls:memo_list' %}">Memos</a>
      </li>
      <li class="nav-item">
        <a class="nav-link active" aria-current="page" href="{% url 'polls:memo_create' %}">Memo create</a>
      </li>
      <li class="nav-item">
        <a class="nav-link active" aria-current="page" href="{% url 'polls:sans' %}">SANS</a>
      </li>
      <li class="nav-item">
        <a class="nav-link active" aria-current="page" href="{% url 'polls:papyrus' %}">PAPYRUS</a>
      </li>
      <li class="nav-item">
        <a class="nav-link active" aria-current="page" href="{% url 'polls:art_create' %}">게시글작성</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Link</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
          Dropdown
        </a>
        <ul class="dropdown-menu">
          {% if user.is_authenticated %}
          <span>{{ user.username }}님</span>
          <li><a class="dropdown-item" href="{% url 'accounts:my_logout' %}">logout</a></li>
          <li><a class="dropdown-item" href="{% url 'polls:my_memo_list' %}">my memo</a></li>
          <li><hr class="dropdown-divider"></li>
          <li><a class="dropdown-item" href="#">Something else here</a></li>
          {% else %}
          <li><a class="dropdown-item" href="{% url 'accounts:my_login' %}">login</a></li>
          <li><a class="dropdown-item" href="#">Another action</a></li>
          <li><hr class="dropdown-divider"></li>
          <li><a class="dropdown-item" href="#">Something else here</a></li>
          
          {% endif %}
        </ul>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled" aria-disabled="true">Disabled</a>
      </li>
    </ul>
    <form action="{% url 'polls:memo_search' %}" method="GET">
    <input type="text" name="q" value="{{ query }}">
    <button type="submit">검색</button>
</form>
    <form class="d-flex" role="search">
      <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search" />
      <button class="btn btn-outline-success" type="submit">Search</button>
    </form>
  </div>
</div>
</nav>

{% if messages %}
    <div class="container mt-3">
        {% for message in messages %}
            <div class="alert alert-{{ message.tags }} alert-dismissible fade show">
                {{ message }}
                <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
            </div>
        {% endfor %}
    </div>
{% endif %}

{% block content %}{% endblock %}
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.7/dist/js/bootstrap.bundle.min.js" integrity="sha384-ndDqU0Gzau9qJ1lfW4pNLlhNTkCfHzAVBReH9diLvGRem5+R9g2FzA8ZGN954O5Q" crossorigin="anonymous"></script>
</body>
</html>